version: 2
jobs:
  build:
    docker:
      - image: geoscienceaustralia/passive-seismic:latest
    working_directory: /root/passive-seismic
    steps:
      - checkout
      - run:
          name: get submodules and prepare bash scripts
          command: |
            git submodule update --init --recursive --remote
            sed -i 's/sudo//g' sc3/createenv.sh
            sed -i 's/sudo//g' iloc_rstt/install_iloc_rstt.sh
      - run:
          name: run bash scripts
          command: |
            ./sc3/createenv.sh
            ./iloc_rstt/install_iloc_rstt.sh
      - run:
          name: install python env
          command: |
            env GEOS_DIR=/usr/include/ pip install --process-dependency-links -e .[dev]
      # - run: make lint
      - run:
          name: run tests
          command: |
            mkdir -p test_output/pytest test_output/flake8 test_output/coverage
            export PATH=/usr/lib64/openmpi/bin:$PATH
            make coverage
            export ELLIPCORR=$PWD/ellip-corr
            pytest ellip-corr/tests/
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/
