version: 2
jobs:
  build:
    docker:
      - image: geoscienceaustralia/passive-seismic:0.1
    working_directory: /root/passive-seismic
    steps:
      - checkout
      - run:
          name: pull submodules and prepare bash scripts
          command: |
            git submodule update --init --recursive --remote
            sed -i 's/sudo//g' sc3/createenv.sh
            sed -i 's/sudo//g' iloc_rstt/install_iloc_rstt.sh
      - run:
          name: run bash scripts
          command: |
            ./sc3/createenv.sh
          # not tested in CI as sc3 is unavailable
          #./iloc_rstt/install_iloc_rstt.sh
      # - run: make lint
      - run:
          name: install python env and run tests
          command: |
            export ELLIPCORR=$PWD/ellip-corr
            export PATH=/usr/lib64/openmpi/bin:$PATH
            env GEOS_DIR=/usr/include/ pip install --process-dependency-links -e .[dev]
            mkdir -p test_output/pytest test_output/flake8 test_output/coverage
            make coverage
            pytest ellip-corr/tests/
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/
